{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.master.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" ( mergeOverwrite .Values.commonLabels .Values.master.commonLabels ) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: svc
    app.kubernetes.io/part-of: inventree-master
  annotations:
    {{- if or .Values.master.service.annotations .Values.master.commonAnnotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( mergeOverwrite .Values.master.service.annotations .Values.master.commonAnnotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  {{- if and .Values.master.service.clusterIP (eq .Values.master.service.type "ClusterIP") }}
  clusterIP: {{ .Values.master.service.clusterIP }}
  {{- end }}
  {{- if .Values.master.service.sessionAffinity }}
  sessionAffinity: {{ .Values.master.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.master.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.master.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.master.service.type "LoadBalancer") (eq .Values.master.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.master.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.master.service.type "LoadBalancer") (not (empty .Values.master.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{- toYaml .Values.master.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.master.service.type "LoadBalancer") (not (empty .Values.master.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.master.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.master.service.type "LoadBalancer") .Values.master.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.master.service.loadBalancerClass }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.master.service.ports.http }}
      {{- if .Values.master.service.targetPort }}
      targetPort: {{ .Values.master.service.targetPort.http }}
      {{- else }}
      targetPort: {{ .Values.master.containerPorts.http }}
      {{- end }}
      {{- if and (or (eq .Values.master.service.type "NodePort") (eq .Values.master.service.type "LoadBalancer")) (not (empty .Values.master.service.nodePorts.http)) }}
      nodePort: {{ .Values.master.service.nodePorts.http }}
      {{- end }}
    {{- if .Values.master.containerPorts.https }}
    - name: https
      port: {{ .Values.master.service.ports.https }}
      {{- if .Values.master.service.targetPort }}
      targetPort: {{ .Values.master.service.targetPort.https }}
      {{- else }}
      targetPort: {{ .Values.master.containerPorts.https }}
      {{- end }}
      {{- if and (or (eq .Values.master.service.type "NodePort") (eq .Values.master.service.type "LoadBalancer")) (not (empty .Values.master.service.nodePorts.https)) }}
      nodePort: {{ .Values.master.service.nodePorts.https }}
      {{- end }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.master.podLabels .Values.master.commonLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
{{- end -}}
