## Inventree

## USER-SUPPLIED VALUES:
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app.env/inventree
#           operator: In
#           values:
#           - "true"
# extraDeploy: null
global:
  imagePullSecrets: null
  imageTag: ""
  storageClass: microk8s-hostpath
commonAnnotations:
  metadata.helm.sh/repo: inventree
  metadata.helm.sh/reop-url: https://gh4-io.github.io/inventree-helm/
master:
  adminEmail: admin@gh4.io
  args: null
  command: null
  extraEnvVars: null
  extraVolumeMounts: null
  extraVolumes: null
  hostAliases: null
  image:
    pullSecrets: null
  nodeAffinityPreset:
    values: null
  password: password
  plugins:
    enabled: true
  rbac:
    rules: null
  secret: |
    %I$DO'ltRA;bqD]m;aoA4Xt"tiF%#.NLbo'QY|AMBY5\'k/Ho5sN7bxo[Idn86Ts(u&JR|k<\CNVDs*2?\f99mn+64NX:m't2iX4
  service:
    extraPorts: null
    loadBalancerSourceRanges: null
  sidecars: null
  tolerations: null
  topologySpreadConstraints: null
  persistence:
    existingClaim: inventree-data-pvc
postgresql:
  auth:
    password: superSecretPassword!
  enabled: true
  image:
    tag: 13.13.0-debian-11-r22
  primary:
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: app.env/inventree
    #           operator: In
    #           values:
    #           - "true"
    extraEnvVars: null
    persistence:
      enabled: true
      existingClaim: inventree-db-pvc
proxy:
  enabled: true
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: app.env/inventree
  #           operator: In
  #           values:
  #           - "true"
  service:
    type: ClusterIP
    ports:
      http: 9000
  ingress:
    enabled: true
    hostname: inventree.local
  dnsResolver: 10.152.183.10  
  extraVolumeMounts:
  - mountPath: /var/www
    name: data
    # persistentVolumeClaim:
    #   claimName: inventree-data
  extraVolumes:
  - name: data
    persistentVolumeClaim:
      claimName: inventree-data
#     mountPath: /var/www
redis:
  enabled: true
  image:
    pullSecrets: null
    tag: 7.2.4-debian-11-r2
  master:
    persistence:
      existingClaim: inventree-redis-pvc
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: app.env/inventree
    #           operator: In
    #           values:
    #           - "true"

